Repository ClearKeep/ck-ios, pull requests merged in 2022-06, with the labels that each got.

#40 Feature/call/CLK32-912-DefaultCallView
  ClearKeep.xcodeproj/project.pbxproj
  ClearKeep/App/Resources/Assets.xcassets/ic_camera.imageset/ic_video.png
  ClearKeep/App/Resources/Assets.xcassets/ic_camera_off.imageset/ic_video_off.png
  ClearKeep/App/Resources/Assets.xcassets/ic_mute.imageset/ic_mute-1.png
  ClearKeep/App/Resources/Assets.xcassets/ic_mute_off.imageset/Contents.json
  ClearKeep/App/Resources/Assets.xcassets/ic_mute_off.imageset/ic_mute.png
  ClearKeep/Scenes/Call/CallInMemoryStore.swift
  ClearKeep/Scenes/Call/CallInteractor.swift
  ClearKeep/Scenes/Call/CallRemoteStore.swift
  ClearKeep/Scenes/Call/CallView.swift
  ClearKeep/Scenes/Call/CallWorker.swift
  ClearKeep/Scenes/Call/Models/CallModel.swift
  ClearKeep/Scenes/Call/Views/CallingView.swift
  ClearKeep/Scenes/Call/Views/InComingVoiceCallView.swift
  ClearKeep/Scenes/Call/Views/VoiceCall.swift
  ClearKeep/Scenes/ChatGroup/Views/ListUser.swift
Labels: enhancement

#63 Feature/chat/CLK32-914-GroupMessageView
  ClearKeep.xcodeproj/project.pbxproj
  ClearKeep/App/Resources/Localize.strings
  ClearKeep/App/Theme/AppImageSet.swift
  ClearKeep/Scenes/Chat/Views/ChatView.swift
  ClearKeep/Scenes/Chat/Views/ForwardView.swift
  Packages/CommonUI/CommonUI/Classes/View/BottomSheet/BottomSheet.swift
  Packages/CommonUI/CommonUI/Classes/View/Extension/View+Extension.swift
  Packages/CommonUI/CommonUI/Classes/View/MessageView/MessageBubleView.swift
  Packages/CommonUI/CommonUI/Classes/View/MessageView/MessagerToolBar.swift
  Packages/CommonUI/CommonUI/Classes/View/MessageView/Utils/MessageUtils.swift
  Packages/CommonUI/CommonUI/Classes/View/MessageView/ViewModels/MessageViewModel.swift
  Packages/CommonUI/CommonUI/Classes/View/TextField/MessageTextField.swift
Labels: enhancement

#69 Feature/home/CLK32-906-Fix GroupChat UI
  ClearKeep.xcodeproj/project.pbxproj
  ClearKeep/App/Resources/Localize.strings
  ClearKeep/Scenes/ChatGroup/ChatGroupView.swift
  ClearKeep/Scenes/ChatGroup/Models/ChatGroupModel.swift
  ClearKeep/Scenes/ChatGroup/Views/CreateGroupView.swift
  ClearKeep/Scenes/ChatGroup/Views/ListUser.swift
Labels: bug

#73 Feature/upgrade invalid
  ClearKeep/App/Resources/Localize.strings
  ClearKeep/Scenes/ChangePassword/ChangePasswordInteractor.swift
  ClearKeep/Scenes/ChangePassword/ChangePasswordWorker.swift
  ClearKeep/Scenes/ChangePassword/Views/ChangePasswordContentView.swift
  ClearKeep/Scenes/FogotPassWord/FogotPasswordInteractor.swift
  ClearKeep/Scenes/FogotPassWord/FogotPasswordWorker.swift
  ClearKeep/Scenes/FogotPassWord/Views/FogotPasswordContentView.swift
  ClearKeep/Scenes/Login/Views/LoginContentView.swift
  ClearKeep/Scenes/NewPassword/NewPasswordInteractor.swift
  ClearKeep/Scenes/NewPassword/NewPasswordView.swift
  ClearKeep/Scenes/NewPassword/NewPasswordWorker.swift
  ClearKeep/Scenes/NewPassword/Views/NewPasswordContenView.swift
  ClearKeep/Scenes/Register/RegisterInteractor.swift
  ClearKeep/Scenes/Register/RegisterWorker.swift
  ClearKeep/Scenes/Register/Views/RegisterContentView.swift
  Packages/CommonUI/CommonUI/Classes/View/TextField/SecureTextField.swift
Labels: authentication

#82 Feature/Update Model
  ClearKeep.xcodeproj/project.pbxproj
  ClearKeep/App/Models/GroupBaseModel.swift
  ClearKeep/App/Models/GroupResponseModel.swift
  ClearKeep/App/Models/GroupsModel.swift
  ClearKeep/App/Models/ProfileModel.swift
  ClearKeep/App/Models/UserInfoModel.swift
  ClearKeep/App/Models/UserInfoResponseModel.swift
  Packages/Model/Model/Classes/IGroupResponseModels.swift
  Packages/Model/Model/Classes/IUser.swift
Labels: enhancement
