Repository ClearKeep/ck-ios, pull requests merged in 2022-05, with the labels that each got.

#57 Feature/commonUI/CLK32-967-Text-field
  ClearKeep/App/Theme/AppImageSet.swift
  ClearKeep/App/Theme/ColorSet.swift
  ClearKeep/Scenes/AdvancedServer/Views/AdvancedContentView.swift
  ClearKeep/Scenes/ChangePassword/Views/ChangePasswordContentView.swift
  ClearKeep/Scenes/ChatGroup/ChatGroupView.swift
  ClearKeep/Scenes/FogotPassWord/Views/FogotPasswordContentView.swift
  ClearKeep/Scenes/Home/Views/HomeHeaderView.swift
  ClearKeep/Scenes/Login/Views/LoginContentView.swift
  ClearKeep/Scenes/NewPassword/Views/NewPasswordContenView.swift
  ClearKeep/Scenes/Register/RegisterView.swift
  ClearKeep/Scenes/Register/Views/RegisterContentView.swift
  ClearKeep/Scenes/Social Login/SocialView.swift
  Packages/CommonUI/CommonUI/Classes/Theme/ColorStyle.swift
  Packages/CommonUI/CommonUI/Classes/Theme/TextInputState.swift
  Packages/CommonUI/CommonUI/Classes/View/TextField/CommonTextField.swift
  Packages/CommonUI/CommonUI/Classes/View/TextField/MultiLineTextField.swift
  Packages/CommonUI/CommonUI/Classes/View/TextField/SearchTextField.swift
  Packages/CommonUI/CommonUI/Classes/View/TextField/SecureTextField.swift
  Packages/CommonUI/CommonUI/Classes/ViewModifier/TextFieldStyle.swift
Labels: authentication

#39 Feature/call/CLK32-916: GroupVoiceCall
  ClearKeep.xcodeproj/project.pbxproj
  ClearKeep/App/Resources/Assets.xcassets/ic_camera.imageset/Contents.json
  ClearKeep/App/Resources/Assets.xcassets/ic_camera.imageset/ic_camera.png
  ClearKeep/App/Resources/Assets.xcassets/ic_camera_off.imageset/Contents.json
  ClearKeep/App/Resources/Assets.xcassets/ic_camera_off.imageset/ic_camera_off.png
  ClearKeep/App/Resources/Assets.xcassets/ic_mute-1.imageset/Contents.json
  ClearKeep/App/Resources/Assets.xcassets/ic_mute-1.imageset/ic_mute-1.png
  ClearKeep/App/Resources/Assets.xcassets/ic_mute.imageset/Contents.json
  ClearKeep/App/Resources/Assets.xcassets/ic_mute.imageset/ic_mute.png
  ClearKeep/App/Resources/Assets.xcassets/ic_speaker-1.imageset/Contents.json
  ClearKeep/App/Resources/Assets.xcassets/ic_speaker-1.imageset/ic_speaker.png
  ClearKeep/App/Resources/Assets.xcassets/ic_speaker_off-1.imageset/Contents.json
  ClearKeep/App/Resources/Assets.xcassets/ic_speaker_off-1.imageset/ic_speaker_off.png
  ClearKeep/App/Resources/Assets.xcassets/ic_speaker_off.imageset/Contents.json
  ClearKeep/App/Resources/Assets.xcassets/ic_speaker_off.imageset/Group 198.png
  ClearKeep/App/Resources/Assets.xcassets/ic_speaker_off.imageset/Group 198@2x.png
  ClearKeep/App/Resources/Assets.xcassets/ic_speaker_off.imageset/Group 198@3x.png
  ClearKeep/App/Resources/Assets.xcassets/ic_video-1.imageset/Contents.json
  ClearKeep/App/Resources/Assets.xcassets/ic_video-1.imageset/ic_video.png
  ClearKeep/App/Resources/Assets.xcassets/ic_video_off-1.imageset/Contents.json
  ClearKeep/App/Resources/Assets.xcassets/ic_video_off-1.imageset/ic_video_off.png
  ClearKeep/App/Resources/Assets.xcassets/ic_video_off.imageset/Contents.json
  ClearKeep/App/Resources/Assets.xcassets/ic_video_off.imageset/Group 200.png
  ClearKeep/App/Resources/Assets.xcassets/ic_video_off.imageset/Group 200@2x.png
  ClearKeep/App/Resources/Assets.xcassets/ic_video_off.imageset/Group 200@3x.png
  ClearKeep/App/Resources/Localize.strings
  ClearKeep/App/Theme/AppImageSet.swift
  ClearKeep/Scenes/GroupCall/GroupCallInMemoryStore.swift
  ClearKeep/Scenes/GroupCall/GroupCallInteractor.swift
  ClearKeep/Scenes/GroupCall/GroupCallRemoteStore.swift
  ClearKeep/Scenes/GroupCall/GroupCallView.swift
  ClearKeep/Scenes/GroupCall/GroupCallWorker.swift
  ClearKeep/Scenes/GroupCall/Models/GroupCallModel.swift
  ClearKeep/Scenes/GroupCall/Views/CallingGroup.swift
  ClearKeep/Scenes/GroupCall/Views/InComingVoiceGroupCall.swift
  ClearKeep/Scenes/GroupCall/Views/VoiceGroupCalled.swift
  Packages/CommonUI/CommonUI/Classes/Theme/IImageSet.swift
  Packages/CommonUI/CommonUI/Classes/View/ImageButton/ImageButtonCall.swift
Labels: enhancement

#52 Feature/Password/CLK32 957-ChangePassword-Implement-API
  ClearKeep/App/Injected/InteractorsContainer.swift
  ClearKeep/App/System/AppEnvironment.swift
  ClearKeep/Scenes/ChangePassword/ChangePasswordInteractor.swift
  ClearKeep/Scenes/ChangePassword/ChangePasswordRemoteStore.swift
  ClearKeep/Scenes/ChangePassword/ChangePasswordView.swift
  ClearKeep/Scenes/ChangePassword/ChangePasswordWorker.swift
  ClearKeep/Scenes/ChangePassword/Views/ChangePasswordContentView.swift
Labels: authentication

#53 feature/Fogotpassword/CLK32 956-Fogotpassword-Implement-API
  ClearKeep/App/Injected/InteractorsContainer.swift
  ClearKeep/App/System/AppEnvironment.swift
  ClearKeep/Scenes/FogotPassWord/FogotPasswordInteractor.swift
  ClearKeep/Scenes/FogotPassWord/FogotPasswordRemoteStore.swift
  ClearKeep/Scenes/FogotPassWord/FogotPasswordWorker.swift
  ClearKeep/Scenes/FogotPassWord/Views/FogotPasswordContentView.swift
  ClearKeep/Scenes/NewPassword/NewPasswordInteractor.swift
  ClearKeep/Scenes/NewPassword/NewPasswordRemoteStore.swift
  ClearKeep/Scenes/NewPassword/NewPasswordWorker.swift
  ClearKeep/Scenes/NewPassword/Views/NewPasswordContenView.swift
Labels: authentication

#61 Feature/login/CLK32-899-TwoFactor-Implement-API
  ClearKeep/App/Injected/InteractorsContainer.swift
  ClearKeep/App/System/AppEnvironment.swift
  ClearKeep/Scenes/TwoFactor/TwoFactorInteractor.swift
  ClearKeep/Scenes/TwoFactor/TwoFactorRemoteStore.swift
  ClearKeep/Scenes/TwoFactor/TwoFactorView.swift
  ClearKeep/Scenes/TwoFactor/TwoFactorWorker.swift
  ClearKeep/Scenes/TwoFactor/Views/TwoFactorContentView.swift
Labels: authentication

#56 Feature/login/CLK32-891-Advanced-Server-View
  ClearKeep.xcodeproj/project.pbxproj
  ClearKeep/App/Resources/Localize.strings
  ClearKeep/App/Theme/AppImageSet.swift
  ClearKeep/Scenes/AdvancedServer/AdvancedSeverView.swift
  ClearKeep/Scenes/AdvancedServer/Views/AdvancedContentView.swift
  ClearKeep/Scenes/Login/LoginView.swift
  ClearKeep/Scenes/Register/Models/RegisterViewError.swift
  ClearKeep/Scenes/Register/RegisterView.swift
  ClearKeep/Scenes/Register/Views/RegisterContentView.swift
  Packages/CommonUI/CommonUI/Classes/View/Button/RoundedButton.swift
  Packages/CommonUI/CommonUI/Classes/View/Button/RoundedGradientButton.swift
  Packages/CommonUI/CommonUI/Classes/ViewModifier/GradientBackground.swift
  Packages/CommonUI/CommonUI/Classes/ViewModifier/NavigationBarStyle.swift
Labels: bug

#58 Feature/fogotpassword/CLK32-888-FogotPassword-View
  ClearKeep.xcodeproj/project.pbxproj
  ClearKeep/App/Resources/Localize.strings
  ClearKeep/Scenes/AdvancedServer/AdvancedSeverView.swift
  ClearKeep/Scenes/AdvancedServer/Views/AdvancedContentView.swift
  ClearKeep/Scenes/FogotPassWord/FogotPasswordView.swift
  ClearKeep/Scenes/FogotPassWord/Views/FogotPasswordContentView.swift
  ClearKeep/Scenes/Login/LoginView.swift
  ClearKeep/Scenes/NewPassword/NewPasswordView.swift
  ClearKeep/Scenes/NewPassword/Views/NewPasswordContenView.swift
  Packages/CommonUI/CommonUI/Classes/View/Button/BackButton.swift
  Packages/CommonUI/CommonUI/Classes/View/Extension/View+Extension.swift
  Packages/CommonUI/CommonUI/Classes/ViewModifier/NavigationBar/NavigationBarGradientStyle.swift
  Packages/CommonUI/CommonUI/Classes/ViewModifier/NavigationBar/NavigationBarPlainStyle.swift
  Packages/CommonUI/CommonUI/Classes/ViewModifier/NavigationBar/NavigationViewModifier.swift
  Packages/CommonUI/CommonUI/Classes/ViewModifier/NavigationBarStyle.swift
Labels: bug

#66 Feature/Add configure headers for GRPC
  ClearKeep.xcodeproj/project.pbxproj
  ClearKeep/App/DependencyResolver/DependencyResolver.swift
  ClearKeep/App/Injected/InteractorsContainer.swift
  ClearKeep/App/System/AppEnvironment.swift
  ClearKeep/Scenes/Home/HomeInteractor.swift
  ClearKeep/Scenes/Home/HomeRemoteStore.swift
  ClearKeep/Scenes/Home/HomeView.swift
  ClearKeep/Scenes/Home/HomeWorker.swift
  ClearKeep/Scenes/Home/Models/Server.swift
  ClearKeep/Scenes/Home/Views/HomeMenuView.swift
  ClearKeep/Scenes/RootView.swift
  Packages/ChatSecure/ChatSecure/Classes/Networking/CLKAuthentication/CLKAuthenticationService.swift
  Packages/ChatSecure/ChatSecure/Classes/Networking/CLKAuthentication/Models/Profile.swift
  Packages/ChatSecure/ChatSecure/Classes/Networking/CLKAuthentication/Models/Server.swift
  Packages/ChatSecure/ChatSecure/Classes/Networking/ChannelStorage.swift
  Packages/ChatSecure/ChatSecure/Classes/Networking/Services/Group/GroupService.swift
  Packages/ChatSecure/ChatSecure/Classes/Networking/Services/Messsage/MessageService.swift
  Packages/ChatSecure/ChatSecure/Classes/Networking/Services/User/UserService.swift
  Packages/ChatSecure/ChatSecure/Classes/PersistentStore/ServerStore.swift
  Packages/ChatSecure/ChatSecure/Classes/SocialAuthentication/SocialLoginService.swift
  Packages/Networking/Networking/Classes/Core/APIService.swift
  Packages/Networking/Networking/Classes/Services/AuthenticationAPIService.swift
  Packages/Networking/Networking/Classes/Services/GroupAPIService.swift
  Packages/Networking/Networking/Classes/Services/MessageAPIService.swift
  Packages/Networking/Networking/Classes/Services/NoteAPIService.swift
  Packages/Networking/Networking/Classes/Services/NotifyAPIService.swift
  Packages/Networking/Networking/Classes/Services/NotifyPushAPIService.swift
  Packages/Networking/Networking/Classes/Services/ServerInfoAPIService.swift
  Packages/Networking/Networking/Classes/Services/SignalAPIService.swift
  Packages/Networking/Networking/Classes/Services/UploadFileAPIService.swift
  Packages/Networking/Networking/Classes/Services/UserAPIService.swift
  Packages/Networking/Networking/Classes/Services/VideoCallAPIService.swift
  Packages/Networking/Networking/Classes/Services/WorkspaceAPIService.swift
Labels: enhancement

#70 Feature/home/CLK32-993-PhoneNumber/CountryCode
  ClearKeep.xcodeproj/project.pbxproj
  ClearKeep/App/Resources/Localize.strings
  ClearKeep/App/Resources/locations.json
  ClearKeep/App/Theme/AppImageSet.swift
  ClearKeep/Scenes/Profile/Models/CountryCodeModel.swift
  ClearKeep/Scenes/Profile/ProfileInMemoryStore.swift
  ClearKeep/Scenes/Profile/ProfileInteractor.swift
  ClearKeep/Scenes/Profile/ProfileRemoteStore.swift
  ClearKeep/Scenes/Profile/ProfileView.swift
  ClearKeep/Scenes/Profile/ProfileWorker.swift
  ClearKeep/Scenes/Profile/Views/CountryCode.swift
  ClearKeep/Scenes/Profile/Views/CurrentPassword.swift
  ClearKeep/Scenes/Profile/Views/UserProfileContentView.swift
  ClearKeep/Scenes/TwoFactor/TwoFactorView.swift
  ClearKeep/Scenes/TwoFactor/Views/TwoFactorContentView.swift
Labels: enhancement
